// Dados das marcas de veículos exportados do banco de dados
export const vehicleBrands = [
  { id: 1, name: "Acura" },
  { id: 2, name: "Agrale" },
  { id: 3, name: "Alfa Romeo" },
  { id: 4, name: "AM Gen" },
  { id: 5, name: "Asia Motors" },
  { id: 6, name: "ASTON MARTIN" },
  { id: 7, name: "Audi" },
  { id: 8, name: "Baby" },
  { id: 9, name: "BMW" },
  { id: 10, name: "BRM" },
  { id: 11, name: "Bugre" },
  { id: 12, name: "BYD" },
  { id: 13, name: "CAB Motors" },
  { id: 14, name: "Cadillac" },
  { id: 15, name: "Caoa Chery" },
  { id: 16, name: "Caoa Chery/Chery" },
  { id: 17, name: "CBT Jipe" },
  { id: 18, name: "CHANA" },
  { id: 19, name: "CHANGAN" },
  { id: 20, name: "Chrysler" },
  { id: 21, name: "Citroën" },
  { id: 22, name: "Cross Lander" },
  { id: 23, name: "D2D Motors" },
  { id: 24, name: "Daewoo" },
  { id: 25, name: "Daihatsu" },
  { id: 26, name: "DFSK" },
  { id: 27, name: "Dodge" },
  { id: 28, name: "EFFA" },
  { id: 29, name: "Engesa" },
  { id: 30, name: "Envemo" },
  { id: 31, name: "Ferrari" },
  { id: 32, name: "FEVER" },
  { id: 33, name: "Fiat" },
  { id: 34, name: "Fibravan" },
  { id: 35, name: "Ford" },
  { id: 36, name: "FOTON" },
  { id: 37, name: "Fyber" },
  { id: 38, name: "GAC" },
  { id: 39, name: "GEELY" },
  { id: 40, name: "GM - Chevrolet" },
  { id: 41, name: "GREAT WALL" },
  { id: 42, name: "Gurgel" },
  { id: 43, name: "GWM" },
  { id: 44, name: "HAFEI" },
  { id: 45, name: "HITECH ELECTRIC" },
  { id: 46, name: "Honda" },
  { id: 47, name: "Hyundai" },
  { id: 48, name: "Isuzu" },
  { id: 49, name: "IVECO" },
  { id: 50, name: "JAC" },
  { id: 51, name: "Jaecoo" },
  { id: 52, name: "Jaguar" },
  { id: 53, name: "Jeep" },
  { id: 54, name: "JINBEI" },
  { id: 55, name: "JPX" },
  { id: 56, name: "Kia Motors" },
  { id: 57, name: "Lada" },
  { id: 58, name: "LAMBORGHINI" },
  { id: 59, name: "Land Rover" },
  { id: 60, name: "Lexus" },
  { id: 61, name: "LIFAN" },
  { id: 62, name: "LOBINI" },
  { id: 63, name: "Lotus" },
  { id: 64, name: "Mahindra" },
  { id: 65, name: "Maserati" },
  { id: 66, name: "Matra" },
  { id: 67, name: "Mazda" },
  { id: 68, name: "Mclaren" },
  { id: 69, name: "Mercedes-Benz" },
  { id: 70, name: "Mercury" },
  { id: 71, name: "MG" },
  { id: 72, name: "MINI" },
  { id: 73, name: "Mitsubishi" },
  { id: 74, name: "Miura" },
  { id: 75, name: "NETA" },
  { id: 76, name: "Nissan" },
  { id: 77, name: "Omoda" },
  { id: 78, name: "Peugeot" },
  { id: 79, name: "Plymouth" },
  { id: 80, name: "Pontiac" },
  { id: 81, name: "Porsche" },
  { id: 82, name: "RAM" },
  { id: 83, name: "RELY" },
  { id: 84, name: "Renault" },
  { id: 85, name: "Rolls-Royce" },
  { id: 86, name: "Rover" },
  { id: 87, name: "Saab" },
  { id: 88, name: "Saturn" },
  { id: 89, name: "Seat" },
  { id: 90, name: "SERES" },
  { id: 91, name: "SHINERAY" },
  { id: 92, name: "smart" },
  { id: 93, name: "SSANGYONG" },
  { id: 94, name: "Subaru" },
  { id: 95, name: "Suzuki" },
  { id: 96, name: "TAC" },
  { id: 97, name: "Toyota" },
  { id: 98, name: "Troller" },
  { id: 99, name: "Volvo" },
  { id: 100, name: "VW - VolksWagen" },
  { id: 101, name: "Wake" },
  { id: 102, name: "Walk" },
  { id: 103, name: "ZEEKR" }
]

export default vehicleBrands
